export const ADD_FILTER = 'ADD_FILTER';
export const SEARCH_TEXT = 'SEARCH_TEXT';
export const CHANGE_ACTIVE = 'CHANGE_ACTIVE';
export const RECEIVE_USERS = 'RECEIVE_USERS';
export const SEARCH_NAME = 'SEARCH NAME';
export const SEARCH_CITY = 'SEARCH_CITY';
export const SEARCH_BIRTHYEAR = 'SEARCH_BIRTHYEAR';
